## Task

Open the script `exercises/exercise_1.R` - you will use it for writing the code 💻.

- find the natural log of 12.43
- log 12.43 to the base 10
- log 12.43 to the base 2
- square root of 225

**Don’t forget to write your code in RStudio’s script editor and source the code into the console.**


## Task

Use R to determine the area of a circle with a diameter of 20 cm and assign the result to a variable called `area_circle`. 

**Google is your friend if you can’t remember the formula 🙂 Also, remember that R already knows about pi.**


## Task

Calculate the cube root of 14 x 0.51. You might need to think creatively for a solution, and remember that R follows the usual order of mathematical operators so you might need to use brackets in your code.


## Task

Let's get back to geological dimension 😊!

Create a vector of dummy MgO analyses of your favorite rocks. Remember, that a vector is of 1 dimension and stores
values of one data type only. You can use function `c()` to create new vector.

Now, calculate some basic stats of your MgO:
- min of MgO
- max of MgO
- mean of MgO
- subset your vector by values above the mean





